from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


PROJECT_ROOT = Path(__file__).resolve().parents[1]
LOCAL_SPEC_PATH = PROJECT_ROOT / "openapi.full.snapshot.json"
FALLBACK_SPEC_PATH = PROJECT_ROOT.parent / "oomol-fusion-sdk-ts" / "openapi.full.snapshot.json"
DEFAULT_OUTPUT_PATH = PROJECT_ROOT / "src" / "oomol_fusion_sdk" / "generated" / "openapi_types.py"


def resolve_default_spec_path() -> Path:
    if LOCAL_SPEC_PATH.exists():
        return LOCAL_SPEC_PATH
    return FALLBACK_SPEC_PATH


def to_pascal_case(value: str) -> str:
    segments = []
    current = []
    for char in value:
        if char.isalnum():
            current.append(char)
        elif current:
            segments.append("".join(current))
            current = []
    if current:
        segments.append("".join(current))
    return "".join(segment[:1].upper() + segment[1:] for segment in segments)


def schema_ref_name(ref: str) -> str:
    return ref.split("/")[-1]


class Renderer:
    def __init__(self, spec: Dict[str, Any]):
        self.spec = spec
        self.components = spec.get("components", {}).get("schemas", {})
        self.emitted: Dict[str, str] = {}

    def render(self) -> str:
        for name, schema in self.components.items():
            self.emit_named_schema(name, schema)

        for path, path_item in self.spec.get("paths", {}).items():
            for method, operation in path_item.items():
                if not isinstance(operation, dict):
                    continue

                name_base = "".join(
                    to_pascal_case(part)
                    for part in path.replace("/v1/", "", 1).replace("{", "").replace("}", "").split("/")
                )

                request_schema = (
                    operation.get("requestBody", {})
                    .get("content", {})
                    .get("application/json", {})
                    .get("schema")
                )
                if request_schema and "$ref" not in request_schema:
                    self.emit_named_schema(f"{name_base}{to_pascal_case(method)}Request", request_schema)

                for status_code, response in operation.get("responses", {}).items():
                    response_schema = (
                        response.get("content", {})
                        .get("application/json", {})
                        .get("schema")
                    )
                    if not response_schema or "$ref" in response_schema:
                        continue
                    self.emit_named_schema(f"{name_base}{status_code}Response", response_schema)

        body = "\n\n".join(self.emitted[name] for name in sorted(self.emitted))
        return (
            "# Auto-generated by scripts/generate_openapi_types.py\n"
            "# Do not edit this file manually.\n\n"
            "from __future__ import annotations\n\n"
            "from typing import Any, Dict, List, TypedDict, Union\n\n"
            "try:\n"
            "    from typing import Literal\n"
            "except ImportError:  # pragma: no cover\n"
            "    from typing_extensions import Literal\n\n\n"
            f"{body}\n"
        )

    def emit_named_schema(self, name: str, schema: Dict[str, Any]) -> None:
        if name in self.emitted:
            return

        if self.can_use_typed_dict(schema):
            self.emitted[name] = self.render_typed_dict(name, schema)
            return

        if "allOf" in schema and self.can_render_all_of_as_typed_dict(schema["allOf"]):
            self.emitted[name] = self.render_all_of_typed_dict(name, schema["allOf"])
            return

        alias = self.render_type(schema, name)
        self.emitted[name] = f"{name} = {alias}"

    def render_type(self, schema: Optional[Dict[str, Any]], inline_name_hint: str) -> str:
        if not schema:
            return "Any"

        if "$ref" in schema:
            ref_name = schema_ref_name(schema["$ref"])
            self.emit_named_schema(ref_name, self.components[ref_name])
            return ref_name

        if "allOf" in schema:
            items = schema["allOf"]
            if self.can_render_all_of_as_typed_dict(items):
                self.emit_named_schema(inline_name_hint, schema)
                return inline_name_hint
            return "Dict[str, Any]"

        if "anyOf" in schema:
            return "Union[{items}]".format(
                items=", ".join(self.render_type(item, f"{inline_name_hint}Option{index + 1}") for index, item in enumerate(schema["anyOf"]))
            )

        if "oneOf" in schema:
            return "Union[{items}]".format(
                items=", ".join(self.render_type(item, f"{inline_name_hint}Option{index + 1}") for index, item in enumerate(schema["oneOf"]))
            )

        if isinstance(schema.get("type"), list):
            variants = []
            for index, type_name in enumerate(schema["type"]):
                variants.append(self.render_type({**schema, "type": type_name}, f"{inline_name_hint}Variant{index + 1}"))
            if len(variants) == 2 and "None" in variants:
                other = variants[0] if variants[1] == "None" else variants[1]
                return f"Union[{other}, None]"
            return "Union[{items}]".format(items=", ".join(variants))

        if "enum" in schema:
            return "Literal[{items}]".format(items=", ".join(repr(item) for item in schema["enum"]))

        type_name = schema.get("type")
        if type_name == "string":
            return "str"
        if type_name == "integer":
            return "int"
        if type_name == "number":
            return "float"
        if type_name == "boolean":
            return "bool"
        if type_name == "null":
            return "None"
        if type_name == "array":
            return "List[{item}]".format(item=self.render_type(schema.get("items"), f"{inline_name_hint}Item"))
        if type_name == "object" or "properties" in schema or "additionalProperties" in schema:
            if self.can_use_typed_dict(schema):
                self.emit_named_schema(inline_name_hint, schema)
                return inline_name_hint
            additional = schema.get("additionalProperties")
            if additional:
                value_type = "Any" if additional is True else self.render_type(additional, f"{inline_name_hint}Value")
                return f"Dict[str, {value_type}]"
            return "Dict[str, Any]"
        return "Any"

    def can_use_typed_dict(self, schema: Dict[str, Any]) -> bool:
        return (
            "$ref" not in schema
            and "allOf" not in schema
            and "anyOf" not in schema
            and "oneOf" not in schema
            and "enum" not in schema
            and (schema.get("type") == "object" or ("type" not in schema and "properties" in schema))
        )

    def can_render_all_of_as_typed_dict(self, items: List[Dict[str, Any]]) -> bool:
        return all("$ref" in item or self.can_use_typed_dict(item) for item in items)

    def render_all_of_typed_dict(self, name: str, items: List[Dict[str, Any]]) -> str:
        base_names: List[str] = []
        merged_schema: Dict[str, Any] = {"type": "object", "properties": {}, "required": []}

        for item in items:
            if "$ref" in item:
                ref_name = schema_ref_name(item["$ref"])
                self.emit_named_schema(ref_name, self.components[ref_name])
                base_names.append(ref_name)
                continue

            merged_schema["properties"].update(item.get("properties", {}))
            merged_schema["required"].extend(item.get("required", []))

        return self.render_typed_dict(name, merged_schema, base_names)

    def render_typed_dict(
        self,
        name: str,
        schema: Dict[str, Any],
        base_names: Optional[List[str]] = None,
    ) -> str:
        base_names = list(base_names or [])
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))

        if not properties and schema.get("additionalProperties") and not base_names:
            additional = schema["additionalProperties"]
            value_type = "Any" if additional is True else self.render_type(additional, f"{name}Value")
            return f"{name} = Dict[str, {value_type}]"

        required_props = [(key, value) for key, value in properties.items() if key in required]
        optional_props = [(key, value) for key, value in properties.items() if key not in required]
        blocks: List[str] = []

        if required_props and optional_props:
            required_name = f"_{name}Required"
            blocks.append(self.build_typed_dict_block(required_name, base_names, required_props, total=True))
            blocks.append(self.build_typed_dict_block(name, [required_name], optional_props, total=False))
            return "\n\n".join(blocks)

        total = not optional_props
        properties_to_render = required_props if required_props else optional_props
        blocks.append(self.build_typed_dict_block(name, base_names, properties_to_render, total=total))
        return "\n\n".join(blocks)

    def build_typed_dict_block(
        self,
        name: str,
        base_names: List[str],
        properties: List[Tuple[str, Dict[str, Any]]],
        total: bool,
    ) -> str:
        header_bases = list(base_names)
        if not header_bases:
            header_bases = ["TypedDict"]

        header = f"class {name}({', '.join(header_bases)}"
        if not total:
            header += ", total=False"
        header += "):"

        if not properties:
            return header + "\n    pass"

        lines = [header]
        for key, value in properties:
            lines.append(f"    {key}: {self.render_type(value, f'{name}{to_pascal_case(key)}')}")
        return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--spec",
        type=Path,
        default=resolve_default_spec_path(),
        help="Path to the OpenAPI snapshot JSON file.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Path to the generated Python module.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.spec.exists():
        raise FileNotFoundError(
            "OpenAPI snapshot not found: {path}. Pass --spec explicitly or add a local snapshot.".format(
                path=args.spec
            )
        )

    spec = json.loads(args.spec.read_text())
    rendered = Renderer(spec).render()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)


if __name__ == "__main__":
    main()
